import { ResourceType } from '../../types/dto.js';
import type { ProviderResourceConfig } from '../types.js';
import {
  mapSalesInvoice,
  mapSupplierInvoice,
  mapCustomer,
  mapSupplier,
  mapJournal,
  mapAccount,
  mapCompanyInformation,
  mapFinancialYear,
} from './mapper.js';

export const fortnoxResourceConfigs: Partial<Record<ResourceType, ProviderResourceConfig>> = {
  [ResourceType.SalesInvoices]: {
    listEndpoint: '/invoices',
    listKey: 'Invoices',
    detailEndpoint: '/invoices/{id}',
    detailKey: 'Invoice',
    idField: 'DocumentNumber',
    mapper: mapSalesInvoice,
    detailMapper: mapSalesInvoice,
    paginated: true,
  },
  [ResourceType.SupplierInvoices]: {
    listEndpoint: '/supplierinvoices',
    listKey: 'SupplierInvoices',
    detailEndpoint: '/supplierinvoices/{id}',
    detailKey: 'SupplierInvoice',
    idField: 'GivenNumber',
    mapper: mapSupplierInvoice,
    detailMapper: mapSupplierInvoice,
    paginated: true,
  },
  [ResourceType.Customers]: {
    listEndpoint: '/customers',
    listKey: 'Customers',
    detailEndpoint: '/customers/{id}',
    detailKey: 'Customer',
    idField: 'CustomerNumber',
    mapper: mapCustomer,
    detailMapper: mapCustomer,
    paginated: true,
  },
  [ResourceType.Suppliers]: {
    listEndpoint: '/suppliers',
    listKey: 'Suppliers',
    detailEndpoint: '/suppliers/{id}',
    detailKey: 'Supplier',
    idField: 'SupplierNumber',
    mapper: mapSupplier,
    detailMapper: mapSupplier,
    paginated: true,
  },
  [ResourceType.Journals]: {
    listEndpoint: '/vouchers',
    listKey: 'Vouchers',
    detailEndpoint: '/vouchers/{series}/{number}',
    detailKey: 'Voucher',
    idField: 'VoucherNumber',
    mapper: mapJournal,
    detailMapper: mapJournal,
    paginated: true,
    needsEntryHydration: true,
  },
  [ResourceType.AccountingAccounts]: {
    listEndpoint: '/accounts',
    listKey: 'Accounts',
    detailEndpoint: '/accounts/{id}',
    detailKey: 'Account',
    idField: 'Number',
    mapper: mapAccount,
    detailMapper: mapAccount,
    paginated: true,
  },
  [ResourceType.AccountingPeriods]: {
    listEndpoint: '/financialyears',
    listKey: 'FinancialYears',
    detailEndpoint: '/financialyears/{id}',
    detailKey: 'FinancialYear',
    idField: 'Id',
    mapper: mapFinancialYear,
    paginated: false,
  },
  [ResourceType.CompanyInformation]: {
    listEndpoint: '/companyinformation',
    listKey: 'CompanyInformation',
    detailEndpoint: '/companyinformation',
    detailKey: 'CompanyInformation',
    idField: '',
    mapper: mapCompanyInformation,
    singleton: true,
  },
};
